### ISSUE TITLE
Unexpected key 'Tier' found in params

### ISSUE THREAD

**Issue by atward** [Advanon/serverless-api-key-upload#3]
Use of `Tier` parameter in SSM requires minimum version of aws-sdk.

Bug:

```
Unexpected Parameter -----------------------------------
 
  Unexpected key 'Tier' found in params
```

Relevant handoff:

```
    at Request.promise (aws-sdk/lib/request.js:778:12)
    at serverless-api-key-upload/index.js:11:78
    at serverless-api-key-upload/src/paramsStore.js:32:15
```

https://github.com/Advanon/serverless-api-key-upload/blob/33200135554394d804333df7902ae9e919f6b4a1/src/paramsStore.js#L19-L32

Inspecting aws-sdk-js shows this is introduced in v2.442.0
https://github.com/aws/aws-sdk-js/blob/e6e000319e42979d4a63ac7059e6ab95cd0ead72/.changes/2.442.0.json#L35

aws-sdk is provided by serverless, so would need minimum version of serverless. Above minimum version added in https://github.com/serverless/serverless/commit/00de26831fb580fe622f734996398e81c2e2e3cf which is first included in v1.45.0

**Comment by atward** [comment]
At a minimum, docs should indicate minimum version of serverless required.

A more complete solution would be to omit and warn when `Tier` is not supported by provider
